version: "3.9"
services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/src
    environment:
      DB_USER: swap
      DB_PASSWORD: secret
      DB_PORT: 5432
      DB_HOST: database
      DB_NAME: swap_dev
      REDIS_URL: redis://localhost
    command: mix run --no-halt
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: swap
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
